### ISSUE TITLE
数据可以提供一下吗？

### ISSUE THREAD

**Issue by lailoo** [Boreaso/ALFramework#1]

**Comment by Boreaso** [comment]
两个公开的数据集：
UrbanSound8k：https://urbansounddataset.weebly.com/urbansound8k.html
SpeechCommands：http://download.tensorflow.org/data/speech_commands_v0.01.tar.gz

**Comment by Boreaso** [comment]
@lailoo 两个公开的数据集：
UrbanSound8k：https://urbansounddataset.weebly.com/urbansound8k.html
SpeechCommands：http://download.tensorflow.org/data/speech_commands_v0.01.tar.gz
